# Generated by Django 4.1.3 on 2022-11-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralDataTable',
            fields=[
                ('epic_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=3)),
                ('house_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredClient',
            fields=[
                ('epic_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=30)),
                ('st_code', models.CharField(max_length=4)),
                ('dist_name', models.CharField(max_length=30)),
                ('dist_no', models.CharField(max_length=4)),
                ('ac_name', models.CharField(max_length=30)),
                ('ac_no', models.CharField(max_length=4)),
                ('part_name', models.CharField(max_length=30)),
                ('part_no', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=4)),
                ('gender', models.CharField(max_length=3)),
                ('rln_name', models.CharField(max_length=50)),
                ('rln_type', models.CharField(max_length=3)),
            ],
        ),
    ]
